set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'Chiel92/vim-autoformat'
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-markdown'
Plugin 'tpope/vim-commentary'
Plugin 'tpope/vim-fugitive'
Plugin 'jiangmiao/auto-pairs'
Plugin 'luochen1990/rainbow'
Plugin 'slim-template/vim-slim.git'
Plugin 'ntpeters/vim-better-whitespace'

call vundle#end()            " required
filetype plugin indent on    " required

syntax on

let g:rainbow_active = 1
set et
set tabstop=4
set colorcolumn=80

" Misc
set number
set hidden
set backspace=indent,eol,start

" Setup Extra whitespace highlighting
highlight ExtraWhitespace ctermbg=red guibg=red
match ExtraWhitespace /\s\+$\| \+\ze\t/
autocmd FileType c,cpp,php,ruby,py,html,twig,java autocmd BufWritePre <buffer> :%s/\s\+$//e
nnoremap <CR> :noh<CR><CR>

" Keymaps
let mapleader=";"
map <leader><space> :NERDTreeToggle<cr>

nnoremap <leader><leader> <C-^>
nnoremap <leader>s <C-W><C-J>
nnoremap <leader>n <C-W><C-K>
nnoremap <leader>r <C-W><C-L>
nnoremap <leader>l <C-W><C-H>

map <leader><F5> :source ~/.vimrc<CR>
